# Generated by Django 2.2.5 on 2019-09-18 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190819_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charmpage',
            name='body',
        ),
    ]
