# Generated by Django 2.2.3 on 2019-08-28 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautyreport', '0002_auto_20190821_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beautyreport',
            options={'get_latest_by': 'date'},
        ),
    ]
