# Generated by Django 2.2.5 on 2019-10-02 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beautyreport', '0005_auto_20190911_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeautyreportDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=256, null=True)),
                ('beautyreport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beautyreport.Beautyreport')),
            ],
        ),
    ]
