# Generated by Django 2.2.5 on 2019-10-02 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beautyreport', '0006_beautyreportdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='beautyreportdocument',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
