# Generated by Django 2.2.5 on 2019-10-02 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beautyreport', '0007_beautyreportdocument_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beautyreportdocument',
            name='user',
        ),
        migrations.AddField(
            model_name='beautyreport',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Document_BR', to='beautyreport.BeautyreportDocument'),
        ),
    ]
