# Generated by Django 2.2.3 on 2019-10-02 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beautyreport', '0008_auto_20191002_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beautyreportdocument',
            name='beautyreport',
        ),
        migrations.AlterField(
            model_name='beautyreport',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Document_BR', to='beautyreport.BeautyreportDocument'),
        ),
    ]
