# Generated by Django 2.2.3 on 2019-08-19 18:07

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(help_text='Address', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, help_text='Birthdate', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(help_text='City', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(help_text='Country Code (e.g. AT)', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_customer',
            field=models.BooleanField(default=False, help_text='Establish if the user is a customer'),
        ),
        migrations.AddField(
            model_name='user',
            name='newsletter',
            field=models.BooleanField(default=False, help_text='Permit Newsletter'),
        ),
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.CharField(help_text='Postal Code', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_data',
            field=models.TextField(help_text='JSON data', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(help_text='Phone Number', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, help_text='Title', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False, help_text='Check if the user is verified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 36 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=36, null=True, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
