# Generated by Django 2.2.3 on 2019-08-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190829_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Email Address', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(error_messages={'unique': 'A user with that phone number already exists.'}, help_text='Phone Number', max_length=40, null=True, unique=True),
        ),
    ]
