# Generated by Django 2.2.3 on 2019-09-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190906_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer_id',
            field=models.CharField(blank=True, help_text='Kundennummer', max_length=36, null=True),
        ),
    ]
