# Generated by Django 2.2.3 on 2019-10-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_password_reset',
            field=models.DateTimeField(blank=True, help_text='Last password reset', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='Email Address', max_length=254, null=True),
        ),
    ]
