# Generated by Django 2.2.9 on 2019-12-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20191016_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gid',
            field=models.CharField(blank=True, help_text='Shopify Customer ID', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='note',
            field=models.CharField(blank=True, help_text='Shopify Customer ID', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='orders_count',
            field=models.IntegerField(blank=True, help_text='Order Count', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='total_spent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total spent amount', max_digits=9, null=True),
        ),
    ]
