# Generated by Django 2.2.9 on 2019-12-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20191227_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, help_text='Country Name', max_length=32, null=True),
        ),
    ]
