# Generated by Django 2.2.3 on 2019-08-21 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anamnese', '0002_auto_20190821_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='anformpage',
            name='user_panel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
