# Generated by Django 2.2.3 on 2019-08-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0005_remove_anformpage_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='anformpage',
            name='uid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
