# Generated by Django 2.2.3 on 2019-08-28 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0006_anformpage_uid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anamnese',
            options={'get_latest_by': 'date'},
        ),
        migrations.RemoveField(
            model_name='anformpage',
            name='uid',
        ),
    ]
