# Generated by Django 2.2.3 on 2019-09-10 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
        ('anamnese', '0007_auto_20190828_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnese',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Coach', to='coach.Coach'),
        ),
    ]
