# Generated by Django 2.2.7 on 2019-11-08 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0009_auto_20190911_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnamneseDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='anamnese',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Document_AN', to='anamnese.AnamneseDocument'),
        ),
    ]
