# Generated by Django 2.2.9 on 2019-12-27 15:50

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20190828_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportspage',
            name='chapters',
            field=wagtail.core.fields.StreamField([('s_chapter', wagtail.core.blocks.StructBlock([('chapter_header', wagtail.core.blocks.CharBlock(blank=True, null=True, required=False)), ('sub_chapters', wagtail.core.blocks.StreamBlock([('s_subchapter', wagtail.core.blocks.StructBlock([('sub_chapter_header', wagtail.core.blocks.CharBlock(blank=True, null=True, required=False)), ('paragraphs', wagtail.core.blocks.StreamBlock([('s_paragraph', wagtail.core.blocks.StructBlock([('statement', wagtail.core.blocks.CharBlock(blank=True, null=True, required=False)), ('paragraph_header', wagtail.core.blocks.CharBlock(blank=True, null=True, required=False)), ('paragraph', wagtail.core.blocks.RichTextBlock(blank=False, classname='full', features=['bold', 'italic', 'underline', 'strikethrough', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'blockquote', 'ol', 'ul', 'hr', 'embed', 'link', 'superscript', 'subscript', 'document-link', 'image', 'code'], null=True))], blank=False, icon='group', label='Paragraph', null=True))], blank=False, null=True))], blank=False, icon='mail', label='Sub Chapter', null=True))], blank=False, null=True))], blank=False, icon='group', label='Chapter', null=True))], null=True),
        ),
    ]
